### ISSUE TITLE
Nice results

### ISSUE THREAD

**Issue by wallabyway** [DassaultSystemes-Technology/dspbr-pt#1]
Quick test - Nice results !

<img width="1668" alt="Screen Shot 2020-04-29 at 8 01 41 PM" src="https://user-images.githubusercontent.com/440241/80667801-fde8cd80-8a54-11ea-86aa-1dee8824d51e.png">

https://sketchfab.com/3d-models/police-drone-7f014be2705844c49152bfa1eb66fd86
Please contact me at thomasfrancis120@gmail.com

http://lighttracer.org/app.html?open=https://dl.dropboxusercontent.com/s/6aadi8vj035zikq/police-drone.glb

**Comment by bsdorra** [comment]
Nice, thanks for sharing!
