### ISSUE TITLE
Markdeep Spec is not rendering

### ISSUE THREAD

**Issue by prideout** [DassaultSystemes-Technology/dspbr-pt#14]
I clicked the links in the README but I see markdown source rather than rendered output.  Looks like a 404 on the markdeep library:

![Screen Shot 2020-08-28 at 2 52 56 PM](https://user-images.githubusercontent.com/1288904/91618025-31bdfc00-e93e-11ea-97eb-7207e476eaa3.png)

**Comment by proog128** [comment]
Seems to work ok now, not sure what caused the issue. It says ERR_CONNECTION_REFUSED in the console. Maybe casual-effects.com was offline during that time? We don't have a local copy of markdeep.min.js in the repo, so the first 404 error is expected.

I now removed the invalid link to local markdeep.min.js and upgraded to markdeep 1.11. I hope it works now, would be great if you could give it a try!
