### ISSUE TITLE
Update to latest specular & volume specifications

### ISSUE THREAD

**Issue by emackey** [DassaultSystemes-Technology/dspbr-pt#19]
In the past few weeks, some changes were made to glTF extension specifications for specular and volume.

Can those changes be reflected in this project?  Thanks!

**Comment by bsdorra** [comment]
Fixed specular parsing with 82eb659. There's no validation scene for textured specular yet, so no guarantee that it gives reasonable results for now. 
Volume should be fine, the missing subsurfaceColor parameter is ignored anyways.
