### ISSUE TITLE
Loading error with KHR_materials_unlit

### ISSUE THREAD

**Issue by echadwick-wayfair** [DassaultSystemes-Technology/dspbr-pt#27]
[metal-rough-transm.zip](https://github.com/DassaultSystemes-Technology/EnterprisePBRShadingModel/files/6717647/metal-rough-transm.zip)

1. https://dassaultsystemes-technology.github.io/dspbr-pt/
2. Drag and drop the unzippped glTF and its resources.
Result: the loading animation never ends. 

3. Disable "use pathtracing".
Result: the glTF model is now visible.

4. Enable "use pathtracing"
Result: the model for "metal-roughness-0.01" reappears, along with the loading animation.

Thanks!

**Comment by bsdorra** [comment]
Fixed in 5caf980. Thanks for the reproducer.
