### ISSUE TITLE
Support for non-indexed and interleaved geometry

### ISSUE THREAD

**Issue by donmccurdy** [DassaultSystemes-Technology/dspbr-pt#32]
The renderer currently fails silently if given the following types of input geometry:

- non-indexed (or mixed index and non-indexed?)
- interleaved attributes
- mixed component types (e.g. some positions uint8, others uint16)

The error seems to be related to [the `mergeBufferGeometries` step](https://github.com/DassaultSystemes-Technology/dspbr-pt/blob/f00480a6336fddbedb0c66601fb67666dc064bf5/src/lib/renderer.ts#L800-L804), which displays an error in the console. I'm not sure if it's possible to proceed without merging? three.js does have a [mergeVertices](https://threejs.org/docs/?q=buffergeom#examples/en/utils/BufferGeometryUtils.mergeVertices) utility that can help with creating an index. The other two (de-quantizing, de-interleaving) would require some custom code here. 

I'm wondering if it would be an option to pre-process the input glTF file with gltf-transform, to normalize the structure for the path tracer, like:

```ts
import { WebIO, VertexLayout } from '@gltf-transform/core';
import { ALL_EXTENSIONS } from '@gltf-transform/extensions';
import { weld, dequantize } from '@gltf-transform/functions';

const io = new WebIO()
  .registerExtensions(ALL_EXTENSIONS)
  .setVertexLayout(VertexLayout.SEPARATE);

// Read.
const document = io.readBinary(inputGLB /* ArrayBuffer */);

// Process.
await document.transform(
  weld(),
  dequantize()
);

// Write.
const outputGLB = io.writeBinary(document);
```

^the `dequantize` function doesn't yet exist, but I could add it if that's of interest.

**Comment by bsdorra** [comment]
Merging is currently necessary. The BVH generation and the renderer expect a continuous, homogenous and non-indexed representation of the scenes geometry. Not very flexible or memory efficient, but it reduces the complexity when fetching the triangle data from a sampler in the pathtracing shader. 
Using `mergeBufferGeometries` (including its limitations) is the result of my laziness to write a proper custom translation, happy to get rid of it. 

gltf-transform as preprocess to transform the data into the expected form sounds great. But, as I need to disentangle the interleaved meshes anyways, I could also add dequantization... Conversely, does (de-)interleaving (vertex-)data sound like a useful functionality to have in gltf-transform?

**Comment by donmccurdy** [comment]
> Conversely, does (de-)interleaving (vertex-)data sound like a useful functionality to have in gltf-transform?

That's already available, added because some loaders don't support interleaved data. three.js supports interleaving of course, but certain packages (including [three-mesh-bvh](https://github.com/gkjohnson/three-mesh-bvh), until recently) don't, and so the option is configurable when writing a document with gltf-transform:

```js
import { WebIO, VertexLayout } from '@gltf-transform/core';
import { ALL_EXTENSIONS } from '@gltf-transform/extensions';

const io = new WebIO()
  .registerExtensions(ALL_EXTENSIONS)
  .setVertexLayout(VertexLayout.SEPARATE); // INTERLEAVED (default) or SEPARATE

const outputGLB = io.writeBinary(document);
```

Perhaps there's a better term for it than 'separate'. 😅

**Comment by bsdorra** [comment]
Added gltf-transform to pre-process the input. Works as expected.
Thanks for the report, and gltf-transform of course! ;)  I'll open a new issue to track "support" for KHR_mesh_quantization

**Comment by donmccurdy** [comment]
Awesome, that was quick! I think the `dequantize()` function will be a pretty quick addition. I've started a PR in https://github.com/donmccurdy/glTF-Transform/pull/431.
