### ISSUE TITLE
ThinWalled vs. IOR?

### ISSUE THREAD

**Issue by echadwick-wayfair** [DassaultSystemes-Technology/dspbr-pt#35]
I am seeing odd results in DSPBR when a glTF model uses Transmission without Volume (thin-walled) and no IOR is specified. (third image below)

However when KHR-materials_ior is added at 1.0 for the air inside the bubble, then the iridescence looks correct. (fourth image below)

Shouldn't the absence of the KHR-materials_volume extension cause thin-walled rendering, which assume air is behind/inside the mesh surface?

![2022-06-09 11_42_59-Enterprise PBR Sample Renderer](https://user-images.githubusercontent.com/40177036/172892157-1c19f87c-7cf0-4573-9b79-c71a69dd4105.jpg)

**Comment by bsdorra** [comment]
After discussing this with @proog128 and checking the spec again, I think that the dspbr-pt behavior makese sense. 
Here's why:

> I am seeing odd results in DSPBR when a glTF model uses Transmission without Volume (thin-walled) and no IOR is specified. (third image below)

Lack of KHR-materials_ior [defaults to IOR of 1.5](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#dielectrics)

> However when KHR-materials_ior is added at 1.0 for the air inside the bubble, then the iridescence looks correct. (fourth image below)

For the thin case, the base-ior doesn't specify the ior of the enclosed volume of the sphere, but the ior of the infinitely thin volume enclosed by two imaginary boundary surface (dashed lines in the img below).
![volume cases](https://raw.githubusercontent.com/KhronosGroup/glTF/main/extensions/2.0/Khronos/KHR_materials_volume/figures/thin-thick.svg)
With this, the base-ior doesn't affect the transmission direction, but it does affect the reflection, which is important for the  interaction with the iridescence layer.

> Shouldn't the absence of the KHR-materials_volume extension cause thin-walled rendering, which assume air is behind/inside the mesh surface?

As mentioned above, the base-ior does have an impact on the reflection behavior, also for thin-walled surfaces.
The iridescence spec defines [two material interfaces](https://github.com/KhronosGroup/glTF/blob/1ad76e411dbb4892cda68806b038b4b7c9ecfcd7/extensions/2.0/Khronos/KHR_materials_iridescence/README.md#material-interfaces) - one from the outside to the thin-film layer and another one from the thin-film to the base material. 
On the second interface, the difference in iridescence-ior and base-ior effectively changes the reflection direction and therefore the iridescence color. When base-ior is similar to iridescence-ior, iridescence should be barely visible (as seen in the third image above). Setting the base-ior to 1.0 increases the difference to iridescene-ior 1.6 and results in a prominent iridescence effect in the fourth image.

The sample viewer seems to handle this differently. @PascalSchoen any thoughts on this?

**Comment by bsdorra** [comment]
> Another difference worth noting: The iridescent colors are rendering differently between glTF Sample Viewer and DSPBR. Which is correct?

I couldn't figure that one out yet. The difference in color seems to be related to the fresnel conversions. It only occurs with dielectrics. For metals sample viewer and dspbr-pt are consistent.

**Comment by PascalSchoen** [comment]
I can second, that the base IOR for doesn't depend on the material being thin-walled transparent or not. Per default, it's 1.5 and you can change it via the IOR extension. What I see is (and this is what you already expected @bsdorra) that the calculation of the F0 value, which is the input for evaluating the iridescence, might be different. The F0 value is then used to calculate the base material IOR. See https://github.com/KhronosGroup/glTF-Sample-Viewer/blob/master/source/Renderer/shaders/iridescence.glsl#L42

To get the proper F0 you need to incorporate metallic and the base color and not only the IOR and specular values. In the end, F0 is a blend between the base color and the specular color with metallic as the blend factor. 

Also in the image from @echadwick-wayfair you can see a slight difference between the one with and without IOR. It's only slightly visible as metallic and a white base color quickly increases the F0 value and thus reaches a high [baseIOR](https://github.com/KhronosGroup/glTF-Sample-Viewer/blob/master/source/Renderer/shaders/iridescence.glsl#L68) value also for low IOR values.

**Comment by PascalSchoen** [comment]
Also important to know: There's a color flip between base IOR values above and below the iridescence IOR. For all base IOR values below the iridescence IOR you get the same color range with changing saturation (getting more saturated the bigger the difference between the two IOR values). The same is true for base IOR values above the iridescence IOR but with a different color range. This is, what can be seen above. The colors in the two pictures on the left are produced if the base IOR is bigger than iridescence IOR of 1.6 and the colors on the right if they are less. 

For the example above you can calculate the baseIOR like this:

baseColor = 1.0
metallic = 0.3
ior_0 = 1.5 => F0_0 = 0.04
ior_1 = 1.0 => F0_1 = 0.0

baseF0 = lerp(F0, baseColor, metallic)
baseF0_0 = lerp(0.04, 1.0, 0.3) = 0.328
baseF0_1 = lerp(0.0, 1.0, 0.3) = 0.3

baseIOR = (1.0 + sqrt(baseF0)) / (1.0 - sqrt(baseF0))
baseIOR_0 = (1.0 + sqrt(0.328)) / (1.0 - sqrt(0.328)) = 3.68
baseIOR_1 = (1.0 + sqrt(0.3)) / (1.0 - sqrt(0.3)) = 3.42

You see, that the baseIOR is very high for both cases and thus you don't see much difference between the two images.

**Comment by bsdorra** [comment]
Got it, thanks for the detailed explanation! Fixing the F0 calculcation brings the results much closer to the sample viewer output.

|ior =1.5|ior=1.0|
|:----:|:----:|
|![image](https://user-images.githubusercontent.com/83220/174819788-90967f7a-8475-413d-a7d8-57233f74770a.png)|![image](https://user-images.githubusercontent.com/83220/174819365-ad05c615-cc7f-4a29-b416-9ede77dcf609.png)|
